/*
 *  Todos los Derechos Reservados © 2013 SAT
 *  Servicio de Administracion Tributaria (SAT).
 *  
 *  Este software contiene informacion propiedad exclusiva del SAT considerada
 *  Confidencial. Queda totalmente prohibido su uso o divulgacion en forma
 *  parcial o total.
 */
package mx.gob.sat.siat.juridica.base.dao.domain.constants;

/**
 * 
 * @author softtek
 * 
 */
public interface DiscriminadorConstants {

    /**
     * Constantes de solicitud
     */
    String SOLICITUD = "0";
    String SOLICITUD_PATRON = "1";
    String SERVICIO_DOS = "02";

    /**
     * Tipos de persona
     */
    String PERSONA_FISICA = "TIPER.FI";
    String PERSONA_MORAL = "TIPER.MR";
    String PERSONA_INTERNA = "TIPER.IN";
    String PERSONA_SISTEMA = "TIPER.SIS";
    String REPRESENTANTE_LEGAL = "TIPERS.RL";
    String SOLICITANTE = "TIPERS.SL";
    String PERSONA_OIR_RECIBIR_NOTIFIACIONES = "TIPERS.NOT";
    String PERSONA_RESIDENTE_EXTRANJERO = "TIPERS.RES";

    /**
     * Tipos de requerimiento
     */
    String REQUERIMIENTO_DATOS = "INFREQ.D";
    String REQUERIMIENTO_DATOS_Y_DOCUMENTOS = "INFREQ.DR";
    String REQUERIMIENTO_DOCUMENTOS = "INFREQ.R";

    String NOTIFICACION_REQUERIMIENTO = "TINOT.RQ";
    String NOTIFICACION_RESOLUCION = "TINOT.RS";
    String NOTIFICACION_REMISION = "TINOT.RM";

    // Asuntos que se notifican
    String ASUNTO_NOTIFICACION_REQUERIMIENTO = "Requerimiento de informaci\u00F3n";
    String ASUNTO_NOTIFICACION_RESOLUCION = "Remisi\u00F3n";
    String ASUNTO_NOTIFICACION_REMISION = "Resoluci\u00F3n";

    String PREFIJO_RRL = "RRL";
    String PREFIJO_CA = "CAL";
    String PREFIJO_CAL_AUTORIZACIONES = "AUL";
    String PREFIJO_CAL_CONSULTAS = "COL";

    /**
     * Modalidad del tramite 1
     */
    String T1_TIPO_TRAMITE_PREFIJO = "10";
    String T1_CLASIFICACION_ARANCELARIA = "10101";

    /**
     * Modalidades del tramite 2
     */
    String T2_TIPO_TRAMITE_PREFIJO = "20";
    String T2_BASE = "20000";
    String T2_BASE_AUTORIZACIONES = "20200";
    String T2_BASE_CONSULTAS = "20100";
    String T2_BASE_AVISOS = "20300";

    String T2_CLASIFICACION_ARANCELARIA = "20101";
    String T2_NO_PAGO_IVA_IMPORTACION_MERCANCIAS = "20102";
    String T2_REGULACION_DE_VEHICULOS = "20103";
    String T2_CONSULTA_MATERIAL_ADUANERA_Y_COMERCIO_EXTERIOR = "20104";
    String T2_CONSULTA_MATERIA_CODIGO_FISCAL_FEDERACION = "20105";
    String T2_CONSULTA_LEY_ISR = "20106";
    String T2_CONSULTA_LEY_IVA = "20107";
    String T2_CONSULTA_LEY_ADUANERA = "20108";
    String T2_CONSULTA_IMPUESTO_ESPECIAL_PRODUCTOS_SERVICIOS = "20109";
    String T2_CONSULTAS_LEY_TENENCIA_VEHICULO = "20110";
    String T2_CONSULTA_MATERIA_IMPUESTO_AUTOS_NUEVOS = "20111";
    String T2_CONSULTA_MATERIA_COORDINACION_FISCAL = "20112";
    String T2_CONSULTA_MATERIA_DERECHOS = "20113";
    String T2_CONSULTA_MATERIA_DECRETOS_PROGRAMAS = "20114";
    String T2_CONSULTA_MATERIA_RESOLUCIONES_GENERALES = "20115";
    String T2_CONSULTA_MATERIA_IMPUESTO_INTERNOS = "20116";
    String T2_CONSULTA_IMPUESTO_ESPECIAL_PRODUCTOS_SERVICIOS_IMPORTACIONES = "20117";

    String T2_MODALIDAD_SECUENCIA_AUTORIZACIONES = "20200";
    String T2_DESTRUCCION_CAMBIO_REGIMEN_MERCANCIAS_DESTRUIDAS_DANIOS_PAIS = "20201";
    String T2_DONACION_DESPERDICIOS_EMPRESAS_IMMEX = "20202";
    String T2_SEGURIDAD_NACIONAL = "20203";
    String T2_TRANSLADO_MERCANCIAS_INTERIOR_PAIS_INDUSTRIA_AUTOMOTRIZ = "20204";
    String T2_PRORROGA_PLAZOS_IMPORTACION_EXPORTACION = "20205";
    String T2_RECTIFICACION_PEDIMENTOS = "20206";
    String T2_DONACION_EXTRANJERO_ART6_FRACCIONXVII_LEY_ADUANERA = "20207";
    String T2_IMPORTACION_UNICA_SIN_PADRON = "20208";
    String T2_IMPORTACION_UNICA_SIN_CONCLUIR_TRAMITE_INSCRIPCION = "20209";
    String T2_CANDADOS_OFICIALES = "20210";
    String T2_MENSAJE_CASA_ART61_FACCIONVII_LA = "20211";
    String T2_DONACION_FISCO_FEDERAL_ART147_RLA = "20212";
    String T2_IMPORTACION_DEFINITIVA_VEHICULOS_ESPECIALES_ADAPTADOS = "20213";
    String T2_RETORNO_SEGURO = "20214";
    String T2_RESARCIMIENTO = "20215";
    String T2_PROVEEDOR_CERTIFICACION_CFDI = "20216";
    String T2_AUTORIZACION_CENTRO_DESTRUCCION_VEHICULOS = "20217";
    String T2_AUTORIZACION_FUSION = "20218";
    String T2_CLAVE_PRODUCIR_IMPORTAR_NUEVAS_MARCAS_TABACO_LABRADOS = "20219";
    String T2_MONEDEROS_ELECTRONICOS = "20220";
    String T2_CONTINUAR_EMITIENDO_MONEDEROS_ELECTRONICOS = "20221";
    String T2_AUTORIZACION_LIBERACION_PAGO_EROGACIONES = "20222";
    String T2_AUTORIZACION_DUDUCCION_PERDIDAS_TITULOS = "20223";
    String T2_AUTORIZACION_NO_DEDUCCION_COSTO_ADQUISICION = "20224";
    String T2_AUTORIZACION_REDUCCION_GASTOS_USO_GOCE_TEMPORAL = "20225";
    String T2_AUTORIZACIONES_DEDUCIR_PAGOS_AVIONES = "20226";
    String T2_AUTORIZACIONES_DEDUCIR_PAGOS_EMBARCACIONES = "20227";
    String T2_AUTORIZACIONES_DEDUCIR_PAGOS_CASA_HABITACION = "20228";
    String T2_AUTORIZACIONES_DEDUCIR_PAGOS_COMEDORES = "20229";
    String T2_AUTORIZACIONES_PROVEEDOR_SERVICIO_AUTORIZADO_PSA = "20230";
    String T2_AUTORIZACIONES_ORGANO_VERIFICADOR_OV = "20231";
    String T2_AUTORIZACIONES_ENAJENAR_ACCIONES_COSTO_FISCAL = "20232";

    String T2_PRORROGAS_IMPORTACION_EXPORTACION_CUADERNOS_ATA = "20233";
    String T2_PRORRGOAS_IMMEX_CANCELADO = "20234";

    String T2_AVISO_RENOVACION_MONEDEROS_ELECTRONICOS = "20235";
    String T2_SOLICITUD_CANCELACION_VEHICULOS_USADOS = "20236";
    String T2_RESARCIMIENTO_ECONOMICO_DESTRUCCION_MERCANCIAS = "20237";
    String T2_RESARCIMIENTO_ECONOMICO_DESCOMPOCISION_ANIMALES = "20238";
    String T2_RESARCIMIENTO_ECONOMICO_ESPECIE = "20239";
    String T2_FRANQUICIA_DIPLOMATICA_VEHICULOS = "20240";    
    String T2_AVISO_RENOVACION_ORGANO_VERIFICADOR = "20301";
    String T2_AVISO_RENOVACION_PROVEEDOR_SERVICIO = "20302";
    String T2_AVISO_RENOVACION_MONEDEROS_VALESDESPENSA = "20303";
    String T2_AVISO_RENOVACION_MONEDEROS_COMBUSTIBLES = "20304";
    String T2_AVISO_ACTUALIZACION_MONEDEROS_COMBUSTIBLES = "20305";
    String T2_AVISO_CERTIFICACION_PROVEEDOR_SERVICIO = "20306";
    String T2_AVISO_ACTUALIZACION_MONEDEROS_ELECTRONICOS = "20307";
    
    String T2_AUTORIZACION_APLICAR_REGIMEN_OPCIONAL_GRUPOS_SOCIEDADES="20241";
    String T2_SOL_AUTO_SOCIEDADES_FINANCIERAS_OBJ_MULTIPLE_NV_CREACION="20266";
    String T2_SOL_AUTO_DIFER_PAGO_ISR_DERIV_REESTRUC_REF_ART161_LEY_ISR="20267";
    String T2_SOL_AUT_NO_APL_DIS_TI_VI_CA_I_LEY_ISR_ING_PAS_GEN_ENT_FIG="20268";
    String T2_AUTO_EXC_INV_ACT_NV_LIMIT_ESTA_REQ_FIDEI_INVER_ENER_INFRA="20269";
    String T2_AUTORIZACION_OPERAR_ORGANO_CERTIFICADOR="20264";
    String T2_SOL_DEJAR_SIN_EFECTOS_AUTOR_OPERAR_ORGANO_CERTIFICADOR="20265";
    String T2_MODALIDAD_20270="20270";
    String T2_MODALIDAD_20271="20271";
    String T2_MODALIDAD_20272="20272";
    String T2_MODALIDAD_20273="20273";
    String T2_MODALIDAD_20274="20274";
    String T2_MODALIDAD_20275="20275";
    String T2_MODALIDAD_20276="20276";
    String T2_MODALIDAD_20277="20277";
    String T2_MODALIDAD_20278="20278";
    String T2_MODALIDAD_20279="20279";
    /*
     * Se agregan para PPMC 96156 E106720   Hidrocarburos 
     *   
     */
    String T2_CONSULTAS_EN_MATERIA_DE_PRECIOS_DE_TRANSFERENCIA="20118";
    String T2_CONSULTAS_EN_MATERIA_DE_LEY_DEL_IMPUESTO_A_LOS_DEPOSITOS_EN_EFECTIVO="20119";
    String T2_CONSULTAS_EN_MATERIA_DE_LEY_DEL_IMPUESTO_EMPRESARIAL_A_TASA_UNICA="20120";
    String T2_CONSULTAS_EN_MATERIA_DE_LEY_DE_INGRESOS_SOBRE_HIDROCARBUROS="20121";
    String T2_AUTORIZACION_FUSION_DENTRO5ANIOS_POSTERIORES_FUSION_O_ESCISION="20247";
    String T2_AUTORIZACION_PARA_LA_DETERMINACION_DE_UN_REGIMEN_FISCAL="20242";
    String T2_AUTORIZACIONES_BAPAS="20243";
    String T2_AUTORIZACIONES_MAPS="20244";
    String T2_AUTORIZACION_DIFERIMIENTO_DE_IMPUESTO_161_LISR="20245";
    String T2_SOLICITUD_DE_RESOLUCION_PARA_DEDUCIR_INTERESES_POR_DEUDAS_ENTRE_PARTES_RELACIONADAS="20246";
}
